### ISSUE TITLE
function error

### ISSUE THREAD

**Issue by SuvarnaBaviskar** [CodeKul/online-android10-06062020#1]
fun foo ()
{
    listOf(1,2,3,4,5).forEach()
    {
        if(it == 3) return
        println(it)
    }
}
fun main()
{
    var cr = foo()
    println(cr.toString())
}

This code give output like---
1
2
kotlin.unit  ----( what is kotlin.unit)

**Comment by aniruddhha** [comment]
in the above code, it is not absolutely necessary to convert cr to string, because function `foo` is returning void i.e unit in kotlin. What would be output of following code in java ?
``` 
void foo() {
}

main() {
System.out.println(foo())
}
```
 
Kindly refer following links for more clarity on unit.

- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/
- https://stackoverflow.com/questions/47893445/possible-to-keep-unit-as-the-return-type-of-a-kotlin-function-when-called-from?rq=1
